---
github_token:
  description: "Github authentication token."
  type: "string"
  secret: true
  required: true
forum_feed_url:
  description: "URL to the forum RSS feed."
  type: "string"
  default: "https://forum.coditation.com/latest.rss"
  required: true
