---
name: "stackstorm_update"
pack: "st2community"
description: "Gather and publish various statistics for previous 24 hours."
enabled: true

trigger:
  type: "core.st2.CronTimer"
  parameters:
    timezone: "UTC"
    day_of_week: '*'
    hour: 17
    minute: 30
    second: 0

action:
  ref: "st2community.build-and-message"
  parameters:
    github_users:
      - "StackStorm"
      - "StackStorm-Exchange"
    channel: "#stackstorm"
    delta:
      days: 1
      minutes: 10
